apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rallly.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_BASE_URL: {{ .Values.baseUrl | quote }}
  SUPPORT_EMAIL: {{ .Values.supportEmail | quote }}
  {{- if .Values.noreplyEmail }}
  NOREPLY_EMAIL: {{ .Values.noreplyEmail | quote }}
  {{- end }}
  {{- if .Values.allowedEmails }}
  ALLOWED_EMAILS: {{ .Values.allowedEmails | quote }}
  {{- end }}
  {{- if .Values.initialAdminEmail }}
  INITIAL_ADMIN_EMAIL: {{ .Values.initialAdminEmail | quote }}
  {{- end }}
  EMAIL_LOGIN_ENABLED: {{ .Values.emailLogin.enabled | quote }}
  REGISTRATION_ENABLED: {{ .Values.registration.enabled | quote }}
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_SECURE: {{ .Values.smtp.secure | quote }}
  {{- if .Values.smtp.user }}
  SMTP_USER: {{ .Values.smtp.user | quote }}
  {{- end }}
  SMTP_REJECT_UNAUTHORIZED: {{ .Values.smtp.rejectUnauthorized | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  OIDC_NAME: {{ .Values.oidc.name | quote }}
  OIDC_DISCOVERY_URL: {{ .Values.oidc.discoveryUrl | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  {{- end }}
  {{- if .Values.garage.enabled }}
  S3_ENDPOINT: {{ printf "http://%s:3900" (include "rallly.garage.fullname" .) | quote }}
  S3_BUCKET_NAME: {{ .Values.garage.bucketName | quote }}
  S3_REGION: garage
  {{- else if .Values.externalS3.endpoint }}
  S3_ENDPOINT: {{ .Values.externalS3.endpoint | quote }}
  S3_BUCKET_NAME: {{ .Values.externalS3.bucketName | quote }}
  S3_REGION: {{ .Values.externalS3.region | quote }}
  {{- end }}
  {{- if .Values.caCert.enabled }}
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/rallly-custom-ca.pem
  {{- end }}
