{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rallly.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_PASSWORD: {{ .Values.secretPassword | quote }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
  DATABASE_URL: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
  {{- if .Values.smtp.password }}
  SMTP_PWD: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if and .Values.oidc.enabled .Values.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if and (not .Values.garage.enabled) .Values.externalS3.endpoint (not .Values.externalS3.existingSecret) }}
  S3_ACCESS_KEY_ID: {{ .Values.externalS3.accessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.externalS3.secretAccessKey | quote }}
  {{- end }}
  {{- if .Values.housekeeping.enabled }}
  CRON_SECRET: {{ .Values.housekeeping.cronSecret | quote }}
  {{- end }}
{{- end }}
