{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rallly.postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
{{- end }}
