{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rallly.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "rallly.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
